### ISSUE TITLE
Docker-compose?

### ISSUE THREAD

**Issue by TimPerry** [avsm/docker-ssh-agent-forward#1]
How would one use this with docker-compose? Thanks!

**Comment by hasMichaels** [comment]
@TimPerry 

I've considered using a docker-compose.yml file similar to the following:

```
pinata-sshd:
      build:
          context: ./docker/<path to your pinata code>
          dockerfile: Dockerfile
      image: pinata-sshd
      container_name: pinata-sshd
      volumes:
          - $HOME/.ssh/known_hosts:/root/.ssh/known_hosts:ro
          - $HOME/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
          - $HOME/.pinata-sshd:/tmp
      ports:
          - "2244:22"
```

Still, you need to run some of the scripts to effectively use this. 
- the script that sets up ports, etc.
  - https://github.com/avsm/docker-ssh-agent-forward/blob/master/pinata-ssh-forward.sh 
- the script that emits parameters for attaching ssh stuff to a container 
  - https://github.com/avsm/docker-ssh-agent-forward/blob/master/pinata-ssh-mount.sh
